#-------------------------------
# General Site Settings
title: Kailey Smith
email: Email:kaileysmith2021@u.northwestern.edu || Chicago IL, US


#-------------------------------
# Author Settings
author:
  name: Kailey Smith
  # image: 01.jpg
  say-hello: <strong>Robotics Engineer</strong>
  bio1: Welcome to my portfolio! Please scroll
  bio2: down to explore my recent projects.
  about-me: About Me


#-------------------------------
# Contact links
github: https://github.com/gingineer95
github-title: github
linkedin: https://www.linkedin.com/in/kailey-smith-188a9411a/
linkedin-title: linkedin
projects: https://gingineer95.github.io/
projects-title: projects
contact: Contact Me
contact-blurb: I look forward to hearing from you!
resume-title: resume
resume: https://gingineer95.github.io/images/Kailey_Smith_Resume.pdf
# resume: https://drive.google.com/file/d/13a8nonvvSNJKjg06VmDgScFiF6Ds8uda/view?usp=sharing
